name: Terraform_deploy
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  deploy_dev:
    uses: ./.github/workflows/terraform-deploy-template.yml
    with:
      environment: Development
      working_directory: ./terraform/modules/main
      tf_vars: ../../environments/dev.tfvars
      backend_config: ../../environments/backend/dev.conf
    secrets:
      azure_ad_client_id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      azure_ad_client_secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      azure_ad_tenant_id: ${{ secrets.AZURE_AD_TENANT_ID }}
      